### ISSUE TITLE
Fixing Tags on Dockerhub

### ISSUE THREAD

**Issue by SquallHalle** [certbot/certbot-docker#10]
you fixed recently the multiarch problem.
Help others to see which arch now are supported and add the matching tags on docker hub.

**Comment by adferrand** [comment]
Unfortunately, since we are using QEMU to build foreign architectures on amd64, there is no way currently to properly set the architecture tags on Docker Hub. See https://github.com/moby/moby/issues/36552 and https://github.com/JSurf/docker-rpi-mariadb/issues/4.

**Comment by Tob1as** [comment]
Maybe this can help: https://github.com/rmoriz/multiarch-test or also one of the fork.

Or: https://github.com/estesp/manifest-tool (i use this with hooks for my arm image)

**Comment by bmw** [comment]
This is now tracked at https://github.com/certbot/certbot/issues/8201.
