### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by J0WI** [certbot/certbot-docker#15]
Add a CI to this repo that generates try builds from PRs and branches and optionally run smoke tests.

**Comment by bmw** [comment]
I agree we should do this. Thanks for making an issue.

I think we'll get most of the way there by simply running `./build.sh <certbot tag>` where ideally `<certbot tag>` is the most recent tag on https://github.com/certbot/certbot.

Adding some basic tests on the built images isn't a bad idea either.

**Comment by bmw** [comment]
I'm closing this in favor of https://github.com/certbot/certbot/issues/8202
