### ISSUE TITLE
Docker Hub - Update dns-cloudflare and dns-dnsmadeeasy images to 1.2.0

### ISSUE THREAD

**Issue by christoph-bessei** [certbot/certbot-docker#19]
The images of [dns-cloudflare](https://hub.docker.com/r/certbot/dns-dnsmadeeasy) and [dns-dnsmadeeasy](https://hub.docker.com/r/certbot/dns-dnsmadeeasy) on Docker Hub are still using certbot v1.1.0.
An update to v1.2.0 would be great, especially for Cloudflare (v1.2.0 supports restricted API tokens).

**Comment by krishofmans** [comment]
We would like to see an updated image as well.

**Comment by bmw** [comment]
Thanks for taking the time to report this!

All of our images are now updated to version 1.2.0.
