### ISSUE TITLE
README should link to relevant Certbot docs

### ISSUE THREAD

**Issue by bmw** [certbot/certbot-docker#2]
There was a bit of confusion on the community forum at https://community.letsencrypt.org/t/is-this-really-an-official-repository/99444 about whether our Docker images are really official images. The only reference to them outside of this separate GitHub org is in https://certbot.eff.org/docs/install.html#running-with-docker which you probably won't see if you just happened to stumble across the images on Docker Hub.

I think one way to help fix this is to link to this section of our docs in the Docker image's README. This has the added benefit of providing more information on how to successfully use these images.

**Comment by prometheanfire** [comment]
ya, for the dns docks, I don't know what environment variables to pass for the key, domain, etc.  The lack of docs for the images makes them not that useful.

**Comment by DavidGoodwin** [comment]
> ya, for the dns docks, I don't know what environment variables to pass for the key, domain, etc. The lack of docs for the images makes them not that useful.

For me, .... change the various example.com bits in the below as appropriate :

```
AWS_ACCESS_KEY_ID=xxx
AWS_SECRET_ACCESS_KEY=yyy

docker run --rm -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
    -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
    -v $(pwd)/certs:/etc/letsencrypt/ \
    certbot/dns-route53 certonly \
    --agree-tos \
    --email=test@example.com \
    --server https://acme-v02.api.letsencrypt.org/directory \
    --dns-route53 \
    --dns-route53-propagation-seconds 30 \
    --preferred-challenges dns \
    --non-interactive \
    -d *.blah.example.com -d blah.example.com

```

**Comment by bmw** [comment]
I just added a link to https://certbot.eff.org/docs/install.html#running-with-docker to all our READMEs.
