### ISSUE TITLE
plugin request: acme-dns

### ISSUE THREAD

**Issue by Germs2004** [certbot/certbot-docker#21]
Certbot doesn't work with Google Domains DNS so acme-dns was made to workaround that problem without having to sign up for another 3rd party DNS service (acme-dns is self-hosted).  It would be helpful to have a certbot plugin to automate the ACME process with acme-dns so that these two Docker containers can generate wildcard certificates for users of Google Domains DNS.

acme-dns Docker:
[https://hub.docker.com/r/joohoi/acme-dns/](https://hub.docker.com/r/joohoi/acme-dns/)
acme-dns Github:
[https://www.github.com/joohoi/acme-dns](https://www.github.com/joohoi/acme-dns)
A useful script from acme-dns that may help with building an official plugin:
[https://github.com/joohoi/acme-dns-certbot-joohoi/blob/master/acme-dns-auth.py](https://github.com/joohoi/acme-dns-certbot-joohoi/blob/master/acme-dns-auth.py)

Thank you

**Comment by bmw** [comment]
The author of acme-dns also is also a member of the Certbot team actually.

This probably won't happen for a while, but we're planning on rethinking our approach to DNS challenges in Certbot in the next year and as part of that may adopt the acme-dns plugin.

**Comment by Germs2004** [comment]
Oh, that's neat to know about the author.  It's reassuring to know that someone so knowledgeable is involved in solving this problem.

You may be interested in this similar plugin that is mentioned on Certbot's wiki: [https://github.com/siilike/certbot-dns-standalone](https://github.com/siilike/certbot-dns-standalone).  For Certbot users, it actually seems better than the acme-dns application because dns-standalone is a direct plugin with Certbot.  So it doesn't require a separate Docker container, HTTP(S) POST API, or script to connect Certbot with acme-dns.  Unfortunately, the developer of that plugin [isn't familiar](https://github.com/siilike/certbot-dns-standalone/issues/7) enough with Docker (nor am I) to get it working in Docker.

**Comment by bmw** [comment]
Thanks for the link! We actually already have a PR from the author to accept that as an official plugin as well: https://github.com/certbot/certbot/pull/6646

**Comment by bmw** [comment]
We have on our roadmap to rethink our approach to DNS challenges in the next year which I think covers this issue so I'm going to close this for now.
