### ISSUE TITLE
Upgrade httplib2 version in docker image

### ISSUE THREAD

**Issue by pengbins** [certbot/certbot-docker#24]
I was trying to use image certbot/certbot:v1.4.0 behind a http proxy. 
But it seems the version of httplib2 used in this image is 0.10.3. 
Which happens to be the last version not respect HTTP_PROXY / HTTPS_PROXY environment variables.
https://github.com/httplib2/httplib2/pull/90

Would anyone help to upgrade httplib2  to a newer version?

**Comment by ohemorange** [comment]
Thanks for reporting, will add this feature request to the queue.

**Comment by bmw** [comment]
This is now tracked at https://github.com/certbot/certbot/issues/8204.
