### ISSUE TITLE
Regularly build/test/deploy these images

### ISSUE THREAD

**Issue by bmw** [certbot/certbot-docker#25]
During our last release, our Docker images failed to build until https://github.com/certbot-docker/certbot-docker/pull/23 landed. I think it's worth spending the time to try and ensure we catch these issues earlier rather than at release time.

To fix this, I think we should build/test/deploy these images nightly. Ideally we should do this for all images, but I think it's possible this will be too slow and we should just test a subset. Whether or not this is too slow requires testing.

As for how to do this, I think we have at least a few options. Probably in my order of preference from least to most preferred:

1. Build (and run smoke tests) on the Docker images built using the latest release tag.
2. Build (and run smoke tests) on the Docker images built using Certbot `master`.
3. Build (and run smoke tests) and deploy the Docker images built using Certbot `master` to something like a `<arch>-nightly` tag on Docker Hub.

While those are my preferences for the end goal, any of these approaches are a significant improvement over what we have now and would have caught the problem we had during our last release. Because of that, I think implementation simplicity should be a major factor here.

A related issue here is https://github.com/certbot-docker/certbot-docker/issues/15.

@joohoi, you expressed interest in working on this issue.

cc @adferrand as I'd be surprised if you didn't have opinions here :smile:

**Comment by adferrand** [comment]
I have so much to say that I will write a dedicated document for that I think :)

**Comment by adferrand** [comment]
The global plan has been set up during last meeting. A design document proposition is not needed anymore.

**Comment by bmw** [comment]
Great! @joohoi, are you still interested in working on this a bit in your spare time and if so, do you have what you need? If you're not planning on working it anymore, no worries, just let us know so we can have someone else pick it up!

**Comment by joohoi** [comment]
I'm still interested in working on this, however that depends largely of the urgency. I'm currently on vacation and won't be able to put much work towards it, but should be able to continue in a few weeks.

**Comment by bmw** [comment]
I think it's probably fine to wait a few weeks if you'll have the time and interest to work on it then. Lets check in again before you start working on it though just to make sure no one else picked this up and we forgot to update the issue.

**Comment by bmw** [comment]
Fixed in https://github.com/certbot/certbot/pull/8193.
