### ISSUE TITLE
Invalid link on dockerhub page

### ISSUE THREAD

**Issue by oleobal** [certbot/certbot-docker#6]
Hello,

The penultimate link in the description on [the Dockerhub page for certbot](https://hub.docker.com/r/certbot/certbot/) links to `https://www.github.com/certbot/certbot-docker.git` (which 404s), but it should link to `https://github.com/certbot-docker/certbot-docker/` (this repo).

That's about it, thanks for the fine work !

**Comment by bmw** [comment]
Thanks for reporting this. I fixed it.
