### ISSUE TITLE
Rebuild image against base image updates

### ISSUE THREAD

**Issue by J0WI** [certbot/certbot-docker#8]
A big advantage of the docker library (https://github.com/certbot/certbot/issues/5540) are automated rebuilds if a base image have been updated.
The current image published on DockerHub has not been rebuild against recent (security) updates of Python and Alpine Linux.

**Comment by adferrand** [comment]
Yes, this is definitely a strong advantage. Could you mark it also in the linked issue?

**Comment by J0WI** [comment]
Done. I also added a note about multiarch builds.

**Comment by bmw** [comment]
We've moved our Docker setup back to our main repo so I'm closing this in favor of https://github.com/certbot/certbot/issues/5540
