### ISSUE TITLE
Do certbot-auto features apply to this image?

### ISSUE THREAD

**Issue by bdeweygit** [certbot/certbot-docker#9]
Is the certbot script installed in this docker image considered `certbot-auto`, implying that cli flags specific to `certbot-auto` have meaning? For example does the `--no-self-upgrade` flag (which is `certbot-auto` only) actually do anything when used with this certbot installation?

**Comment by bmw** [comment]
No. Flags like that are noops and accepted by Certbot only for compatibility with certbot-auto.
